### ISSUE TITLE
Ver 0.6.2 request error dump

### ISSUE THREAD

**Issue by rexlogic** [knowledgecode/date-and-time#13]
2018-07-09T20:52:34.185664+00:00 app[web.1]: /app/node_modules/date-and-time/date-and-time.js:231

2018-07-09T20:52:34.185668+00:00 app[web.1]:         return new Date(dateObj.getTime() + milliseconds);

2018-07-09T20:52:34.185670+00:00 app[web.1]:                                 ^

2018-07-09T20:52:34.185671+00:00 app[web.1]: 

2018-07-09T20:52:34.185672+00:00 app[web.1]: TypeError: dateObj.getTime is not a function

2018-07-09T20:52:34.185674+00:00 app[web.1]:     at Object.date.addMilliseconds (/app/node_modules/date-and-time/date-and-time.js:231:33)

2018-07-09T20:52:34.185675+00:00 app[web.1]:     at Object.date.addMinutes (/app/node_modules/date-and-time/date-and-time.js:211:21)

2018-07-09T20:52:34.185676+00:00 app[web.1]:     at Object.date.format (/app/node_modules/date-and-time/date-and-time.js:84:22)

**Comment by knowledgecode** [comment]
```
2018-07-09T20:52:34.185672+00:00 app[web.1]: TypeError: dateObj.getTime is not a function
```
Perhaps you are passing something other than a Date object to the first argument of the `format()` method. For example, Number, String, ... or undefined.
