### ISSUE TITLE
It does not support Node.js 8

### ISSUE THREAD

**Issue by jeaxnew** [knowledgecode/date-and-time#78]
Unexpected token =
/tmp/function/node_modules/date-and-time/date-and-time.js:217
        dt.H ||= dt.H || parser.h12(dt.h, dt.A);
               ^

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/function/index.obj.js:6:14)

**Comment by knowledgecode** [comment]
Thank you for your report. I've fixed it.
